// Header automatically generated by MiawKit. Do not edit.
// Generated on Thu Oct 23 22:06:21 2014

#import <Foundation/Foundation.h>

#ifndef MK_LOCALIZATION_KEYS
#define MK_LOCALIZATION_KEYS

/*!
 * BMEAccessLocalization strings file 
 */
static NSString * const BMEAccessLocalization = @"BMEAccessLocalization";

/*!
 * BMEAppDelegateLocalizationTable strings file 
 */
static NSString * const BMEAppDelegateLocalizationTable = @"BMEAppDelegateLocalizationTable";

/*!
 * BMEBlindIntroLocalizationTable strings file 
 */
static NSString * const BMEBlindIntroLocalizationTable = @"BMEBlindIntroLocalizationTable";

/*!
 * BMEBlindMainLocalizationTable strings file 
 */
static NSString * const BMEBlindMainLocalizationTable = @"BMEBlindMainLocalizationTable";

/*!
 * BMECallLocalizationTable strings file 
 */
static NSString * const BMECallLocalizationTable = @"BMECallLocalizationTable";

/*!
 * BMEForgotPasswordLocalizationTable strings file 
 */
static NSString * const BMEForgotPasswordLocalizationTable = @"BMEForgotPasswordLocalizationTable";

/*!
 * BMEFrontPageLocalizationTable strings file 
 */
static NSString * const BMEFrontPageLocalizationTable = @"BMEFrontPageLocalizationTable";

/*!
 * BMEHelperIntroLocalizationTable strings file 
 */
static NSString * const BMEHelperIntroLocalizationTable = @"BMEHelperIntroLocalizationTable";

/*!
 * BMEHelperMainLocalizationTable strings file 
 */
static NSString * const BMEHelperMainLocalizationTable = @"BMEHelperMainLocalizationTable";

/*!
 * BMELanguagesLocalizationTable strings file 
 */
static NSString * const BMELanguagesLocalizationTable = @"BMELanguagesLocalizationTable";

/*!
 * BMELoginLocalizationTable strings file 
 */
static NSString * const BMELoginLocalizationTable = @"BMELoginLocalizationTable";

/*!
 * BMEMainLocalizationTable strings file 
 */
static NSString * const BMEMainLocalizationTable = @"BMEMainLocalizationTable";

/*!
 * BMEPrivacyPolicyLocalizationTable strings file 
 */
static NSString * const BMEPrivacyPolicyLocalizationTable = @"BMEPrivacyPolicyLocalizationTable";

/*!
 * BMERegisteredLocalizationTable strings file 
 */
static NSString * const BMERegisteredLocalizationTable = @"BMERegisteredLocalizationTable";

/*!
 * BMEReportAbuseLocalizationTable strings file 
 */
static NSString * const BMEReportAbuseLocalizationTable = @"BMEReportAbuseLocalizationTable";

/*!
 * BMESecretSettingsLocalizationTable strings file 
 */
static NSString * const BMESecretSettingsLocalizationTable = @"BMESecretSettingsLocalizationTable";

/*!
 * BMESettingsLocalizationTable strings file 
 */
static NSString * const BMESettingsLocalizationTable = @"BMESettingsLocalizationTable";

/*!
 * BMESignUpLocalizationTable strings file 
 */
static NSString * const BMESignUpLocalizationTable = @"BMESignUpLocalizationTable";

/*!
 * BMESignUpMethodLocalizationTable strings file 
 */
static NSString * const BMESignUpMethodLocalizationTable = @"BMESignUpMethodLocalizationTable";

/*!
 * BMESnoozeRelativeDateLocalizationTable strings file 
 */
static NSString * const BMESnoozeRelativeDateLocalizationTable = @"BMESnoozeRelativeDateLocalizationTable";

/*!
 * BMETermsLocalizationTable strings file 
 */
static NSString * const BMETermsLocalizationTable = @"BMETermsLocalizationTable";

/*!
 * BMEVideoLocalizationTable strings file 
 */
static NSString * const BMEVideoLocalizationTable = @"BMEVideoLocalizationTable";

/*!
 * Localizable strings file 
 */
static NSString * const Localizable = @"Localizable";

/*!
 * InfoPlist strings file 
 */
static NSString * const InfoPlist = @"InfoPlist";

/*!
 * "Please enable the following to fully join the Be My Eyes network"

 * All translations:

 * @b da@: "Please enable the following to fully join the Be My Eyes network"

 * @b en@: "Please enable the following to fully join the Be My Eyes network"

 */
static NSString * const BME_ACCESS_INTRO_MESSAGE = @"BME_ACCESS_INTRO_MESSAGE";

/*!
 * "Notifications"

 * All translations:

 * @b da@: "Notifications"

 * @b en@: "Notifications"

 */
static NSString * const BME_ACCESS_NOTIFICATIONS_TITLE = @"BME_ACCESS_NOTIFICATIONS_TITLE";

/*!
 * "When a blind person needs your help, we notify you about the incoming call."

 * All translations:

 * @b da@: "When a blind person needs your help, we notify you about the incoming call."

 * @b en@: "When a blind person needs your help, we notify you about the incoming call."

 */
static NSString * const BME_ACCESS_NOTIFICATIONS_EXPLANATION_HELPER = @"BME_ACCESS_NOTIFICATIONS_EXPLANATION_HELPER";

/*!
 * "Microphone"

 * All translations:

 * @b da@: "Microphone"

 * @b en@: "Microphone"

 */
static NSString * const BME_ACCESS_MICROPHONE_TITLE = @"BME_ACCESS_MICROPHONE_TITLE";

/*!
 * "To be able to talk with and guide the blind person"

 * All translations:

 * @b da@: "To be able to talk with and guide the blind person"

 * @b en@: "To be able to talk with and guide the blind person"

 */
static NSString * const BME_ACCESS_MICROPHONE_EXPLANATION_HELPER = @"BME_ACCESS_MICROPHONE_EXPLANATION_HELPER";

/*!
 * "To be able to explain your problem to the helper."

 * All translations:

 * @b da@: "To be able to explain your problem to the helper."

 * @b en@: "To be able to explain your problem to the helper."

 */
static NSString * const BME_ACCESS_MICROPHONE_EXPLANATION_BLIND = @"BME_ACCESS_MICROPHONE_EXPLANATION_BLIND";

/*!
 * "Camera"

 * All translations:

 * @b da@: "Camera"

 * @b en@: "Camera"

 */
static NSString * const BME_ACCESS_CAMERA_TITLE = @"BME_ACCESS_CAMERA_TITLE";

/*!
 * "Even though we don't send your video to the person you're helping, this is necessary due to technicalities."

 * All translations:

 * @b da@: "Even though we don't send your video to the person you're helping, this is necessary due to technicalities."

 * @b en@: "Even though we don't send your video to the person you're helping, this is necessary due to technicalities."

 */
static NSString * const BME_ACCESS_CAMERA_EXPLANATION_HELPER = @"BME_ACCESS_CAMERA_EXPLANATION_HELPER";

/*!
 * "Your camera content is shown to the helpers."

 * All translations:

 * @b da@: "Your camera content is shown to the helpers."

 * @b en@: "Your camera content is shown to the helpers."

 */
static NSString * const BME_ACCESS_CAMERA_EXPLANATION_BLIND = @"BME_ACCESS_CAMERA_EXPLANATION_BLIND";

/*!
 * "Push notifications are a central part of the Be My Eyes app and you must have them enabled to sign up."

 * All translations:

 * @b da@: "Push-meddelelser er en central del af Be My Eyes appen og du skal have dem slået til for at tilmelde dig."

 * @b en@: "Push notifications are a central part of the Be My Eyes app and you must have them enabled to sign up."

 */
static NSString * const BME_APP_DELEGATE_ALERT_PUSH_NOT_ENABLED_MESSAGE = @"BME_APP_DELEGATE_ALERT_PUSH_NOT_ENABLED_MESSAGE";

/*!
 * "Push notifications not enabled"

 * All translations:

 * @b da@: "Push-meddelelser ikke aktiveret"

 * @b en@: "Push notifications not enabled"

 */
static NSString * const BME_APP_DELEGATE_ALERT_PUSH_NOT_ENABLED_TITLE = @"BME_APP_DELEGATE_ALERT_PUSH_NOT_ENABLED_TITLE";

/*!
 * "Someone"

 * All translations:

 * @b da@: "Nogen"

 * @b en@: "Someone"

 */
static NSString * const BME_APP_DELEGATE_ALERT_PUSH_REQUEST_DEFAULT_NAME = @"BME_APP_DELEGATE_ALERT_PUSH_REQUEST_DEFAULT_NAME";

/*!
 * "Your help is needed!"

 * All translations:

 * @b da@: "Der er brug for din hjælp!"

 * @b en@: "Your help is needed!"

 */
static NSString * const BME_APP_DELEGATE_ALERT_PUSH_REQUEST_TITLE = @"BME_APP_DELEGATE_ALERT_PUSH_REQUEST_TITLE";

/*!
 * "Cancel"

 * All translations:

 * @b da@: "Annuller"

 * @b en@: "Cancel"

 */
static NSString * const BME_APP_DELEGATE_ALERT_PUSH_REQUEST_CANCEL = @"BME_APP_DELEGATE_ALERT_PUSH_REQUEST_CANCEL";

/*!
 * "You must give the application permission to use your microphone in the system settings."

 * All translations:

 * @b da@: "Du skal give programmet tilladelse til at bruge din mikrofon i systemindstillingerne."

 * @b en@: "You must give the application permission to use your microphone in the system settings."

 */
static NSString * const BME_APP_DELEGATE_ALERT_MICROPHONE_DISABLED_MESSAGE = @"BME_APP_DELEGATE_ALERT_MICROPHONE_DISABLED_MESSAGE";

/*!
 * "Microphone not enabled"

 * All translations:

 * @b da@: "Mikrofon ikke aktiveret"

 * @b en@: "Microphone not enabled"

 */
static NSString * const BME_APP_DELEGATE_ALERT_MICROPHONE_DISABLED_TITLE = @"BME_APP_DELEGATE_ALERT_MICROPHONE_DISABLED_TITLE";

/*!
 * "You must give the application permission to use your camera in the system settings."

 * All translations:

 * @b da@: "Du skal give programmet tilladelse til at bruge dit kamera i systemindstillingerne."

 * @b en@: "You must give the application permission to use your camera in the system settings."

 */
static NSString * const BME_APP_DELEGATE_ALERT_CAMERA_DISABLED_MESSAGE = @"BME_APP_DELEGATE_ALERT_CAMERA_DISABLED_MESSAGE";

/*!
 * "Camera not enabled"

 * All translations:

 * @b da@: "Kamera ikke aktiveret"

 * @b en@: "Camera not enabled"

 */
static NSString * const BME_APP_DELEGATE_ALERT_CAMERA_DISABLED_TITLE = @"BME_APP_DELEGATE_ALERT_CAMERA_DISABLED_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_APP_DELEGATE_ALERT_ACCESS_DISABLED_CANCEL = @"BME_APP_DELEGATE_ALERT_ACCESS_DISABLED_CANCEL";

/*!
 * "Cancel"

 * All translations:

 * @b da@: "Annuller"

 * @b en@: "Cancel"

 */
static NSString * const BME_APP_DELEGATE_ALERT_ACCESS_DISABLED_CANCEL_CAN_GO_TO_SETTINGS = @"BME_APP_DELEGATE_ALERT_ACCESS_DISABLED_CANCEL_CAN_GO_TO_SETTINGS";

/*!
 * "Open settings"

 * All translations:

 * @b da@: "Åben indstillinger"

 * @b en@: "Open settings"

 */
static NSString * const BME_APP_DELEGATE_ALERT_ACCESS_DISABLED_GO_TO_SETTINGS = @"BME_APP_DELEGATE_ALERT_ACCESS_DISABLED_GO_TO_SETTINGS";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_APP_DELEGATE_ALERT_PENDING_REQUEST_HANDLED_CANCEL = @"BME_APP_DELEGATE_ALERT_PENDING_REQUEST_HANDLED_CANCEL";

/*!
 * "The pending request has been answered or was cancelled by the blind but thank you for helping out!"

 * All translations:

 * @b da@: "Anmodningen er blevet besvaret eller blev annulleret af blind, men tak for din hjælp!"

 * @b en@: "The pending request has been answered or was cancelled by the blind but thank you for helping out!"

 */
static NSString * const BME_APP_DELEGATE_ALERT_PENDING_REQUEST_HANDLED_MESSAGE = @"BME_APP_DELEGATE_ALERT_PENDING_REQUEST_HANDLED_MESSAGE";

/*!
 * "Request already answered or cancelled"

 * All translations:

 * @b da@: "Anmodning allerede besvaret eller annulleret"

 * @b en@: "Request already answered or cancelled"

 */
static NSString * const BME_APP_DELEGATE_ALERT_PENDING_REQUEST_HANDLED_TITLE = @"BME_APP_DELEGATE_ALERT_PENDING_REQUEST_HANDLED_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_APP_DELEGATE_ALERT_PENDING_REQUEST_NOT_LOADED_CANCEL = @"BME_APP_DELEGATE_ALERT_PENDING_REQUEST_NOT_LOADED_CANCEL";

/*!
 * "The pending request could not be loaded. Don't worry, someone else will answer the request."

 * All translations:

 * @b da@: "Anmodningen kunne ikke indlæses. Bare rolig, en anden vil besvare forespørgslen."

 * @b en@: "The pending request could not be loaded. Don't worry, someone else will answer the request."

 */
static NSString * const BME_APP_DELEGATE_ALERT_PENDING_REQUEST_NOT_LOADED_MESSAGE = @"BME_APP_DELEGATE_ALERT_PENDING_REQUEST_NOT_LOADED_MESSAGE";

/*!
 * "Request not loaded"

 * All translations:

 * @b da@: "Anmodning ikke indlæst"

 * @b en@: "Request not loaded"

 */
static NSString * const BME_APP_DELEGATE_ALERT_PENDING_REQUEST_NOT_LOADED_TITLE = @"BME_APP_DELEGATE_ALERT_PENDING_REQUEST_NOT_LOADED_TITLE";

/*!
 * "Loading..."

 * All translations:

 * @b da@: "Indlæser..."

 * @b en@: "Loading..."

 */
static NSString * const BME_APP_DELEGATE_OVERLAY_LOADING_PENDING_REQUEST_TITLE = @"BME_APP_DELEGATE_OVERLAY_LOADING_PENDING_REQUEST_TITLE";

/*!
 * "Could not register"

 * All translations:

 * @b da@: "Kunne ikke registrere"

 * @b en@: "Could not register"

 */
static NSString * const BME_APP_DELEGATE_ALERT_FAILED_REGISTERING_REMOTE_NOTIFICATIONS_TITLE = @"BME_APP_DELEGATE_ALERT_FAILED_REGISTERING_REMOTE_NOTIFICATIONS_TITLE";

/*!
 * "The device was not registered to receive push notifications. This could mean that the application has been incorrectly signed."

 * All translations:

 * @b da@: "Enheden kunne ikke registreres til at modtage push notifikationer. Dette kan betyde, at applikationen ikke er blevet rigtigt signed."

 * @b en@: "The device was not registered to receive push notifications. This could mean that the application has been incorrectly signed."

 */
static NSString * const BME_APP_DELEGATE_ALERT_FAILED_REGISTERING_REMOTE_NOTIFICATIONS_MESSAGE = @"BME_APP_DELEGATE_ALERT_FAILED_REGISTERING_REMOTE_NOTIFICATIONS_MESSAGE";

/*!
 * "Back"

 * All translations:

 * @b da@: "Tilbage"

 * @b en@: "Back"

 */
static NSString * const BME_BLIND_INTRO_BACK = @"BME_BLIND_INTRO_BACK";

/*!
 * "Continue"

 * All translations:

 * @b da@: "Fortsæt"

 * @b en@: "Continue"

 */
static NSString * const BME_BLIND_INTRO_CONTINUE = @"BME_BLIND_INTRO_CONTINUE";

/*!
 * "The app will put you in live contact with a sighted helper who remotely will assist you with tasks that requires assistance from a sighted person - through a live video connection the helper will tell you what he or she sees when you point your phone at something.\n\nThe helpers in the Be My Eyes network are volunteers and we cannot guarantee the quality of their help or take responsibility for any of their actions. Furthermore because we rely on real people to help you we encourage you to be patient when you request help.\n\nYou may under no circumstances share any nude, unlawful, hateful or sexually suggestive content via the service, and you should never show any sensitive information such as credit cards, passport or other personal information."

 * All translations:

 * @b da@: "Appen vil sætte dig i direkte kontakt med en seende hjælper som vil assistere dig med opgaver som kræver assistance fra en seende person - gennem en direkte video forbindelse vil hjælperen fortælle hvad han eller hun ser når du peger din telefon mod noget.\n\nHjælperne i Be My Eyes netværket er frivillige og vi kan ikke garanterer kvaliteten af deres hjælp eller tage ansvar for deres handlinger. Desuden, da vi er afhængige af virkelige personer til at hjælpe dig opfordrer vi dig til at være toldmodig når du anmoder om hjælp.\n\nDu må under ingen omstændigheder dele nøgent, ulovligt, hadefuldt eller seksuelt ladet indhold gennem tjenesten, og du bør aldrig vise følsomme oplysninger så som kreditkort, pas eller anden personlig information."

 * @b en@: "The app will put you in live contact with a sighted helper who remotely will assist you with tasks that requires assistance from a sighted person - through a live video connection the helper will tell you what he or she sees when you point your phone at something.\n\nThe helpers in the Be My Eyes network are volunteers and we cannot guarantee the quality of their help or take responsibility for any of their actions. Furthermore because we rely on real people to help you we encourage you to be patient when you request help.\n\nYou may under no circumstances share any nude, unlawful, hateful or sexually suggestive content via the service, and you should never show any sensitive information such as credit cards, passport or other personal information."

 */
static NSString * const BME_BLIND_INTRO_DESCRIPTION = @"BME_BLIND_INTRO_DESCRIPTION";

/*!
 * "Connect to first available helper"

 * All translations:

 * @b da@: "Forbind til første tilgængelige hjælper"

 * @b en@: "Connect to first available helper"

 */
static NSString * const BME_BLIND_MAIN_CONNECT_TO_COMMUNITY = @"BME_BLIND_MAIN_CONNECT_TO_COMMUNITY";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_BLIND_MAIN_ALERT_FAILED_CREATING_REQUEST_CANCEL = @"BME_BLIND_MAIN_ALERT_FAILED_CREATING_REQUEST_CANCEL";

/*!
 * "The request could not be created. Please try again."

 * All translations:

 * @b da@: "Anmodningen kunne ikke oprettes. Prøv venligst igen."

 * @b en@: "The request could not be created. Please try again."

 */
static NSString * const BME_BLIND_MAIN_ALERT_FAILED_CREATING_REQUEST_MESSAGE = @"BME_BLIND_MAIN_ALERT_FAILED_CREATING_REQUEST_MESSAGE";

/*!
 * "Failed creating request"

 * All translations:

 * @b da@: "Kunne ikke oprette anmodning"

 * @b en@: "Failed creating request"

 */
static NSString * const BME_BLIND_MAIN_ALERT_FAILED_CREATING_REQUEST_TITLE = @"BME_BLIND_MAIN_ALERT_FAILED_CREATING_REQUEST_TITLE";

/*!
 * "Creating request..."

 * All translations:

 * @b da@: "Opretter anmodning..."

 * @b en@: "Creating request..."

 */
static NSString * const BME_BLIND_MAIN_HUD_CREATING_REQUEST_TITLE = @"BME_BLIND_MAIN_HUD_CREATING_REQUEST_TITLE";

/*!
 * "Disconnect"

 * All translations:

 * @b da@: "Afbryd"

 * @b en@: "Disconnect"

 */
static NSString * const BME_CALL_DISCONNECT = @"BME_CALL_DISCONNECT";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_CALL_ALERT_FAILED_ANSWERING_REQUEST_ANSWERED_CANCEL = @"BME_CALL_ALERT_FAILED_ANSWERING_REQUEST_ANSWERED_CANCEL";

/*!
 * "The request has already been answered. Thanks for your help!"

 * All translations:

 * @b da@: "Anmodningen er allerede blevet besvaret. Tak for din hjælp!"

 * @b en@: "The request has already been answered. Thanks for your help!"

 */
static NSString * const BME_CALL_ALERT_FAILED_ANSWERING_REQUEST_ANSWERED_MESSAGE = @"BME_CALL_ALERT_FAILED_ANSWERING_REQUEST_ANSWERED_MESSAGE";

/*!
 * "Request already answered"

 * All translations:

 * @b da@: "Anmodning allerede besvaret"

 * @b en@: "Request already answered"

 */
static NSString * const BME_CALL_ALERT_FAILED_ANSWERING_REQUEST_ANSWERED_TITLE = @"BME_CALL_ALERT_FAILED_ANSWERING_REQUEST_ANSWERED_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_CALL_ALERT_FAILED_ANSWERING_REQUEST_STOPPED_CANCEL = @"BME_CALL_ALERT_FAILED_ANSWERING_REQUEST_STOPPED_CANCEL";

/*!
 * "The blind has cancelled the request. Thanks for your help!"

 * All translations:

 * @b da@: "Den blinde har annulleret anmodningen. Tak for din hjælp!"

 * @b en@: "The blind has cancelled the request. Thanks for your help!"

 */
static NSString * const BME_CALL_ALERT_FAILED_ANSWERING_REQUEST_STOPPED_MESSAGE = @"BME_CALL_ALERT_FAILED_ANSWERING_REQUEST_STOPPED_MESSAGE";

/*!
 * "Request cancelled"

 * All translations:

 * @b da@: "Anmodning aflyst"

 * @b en@: "Request cancelled"

 */
static NSString * const BME_CALL_ALERT_FAILED_ANSWERING_REQUEST_STOPPED_TITLE = @"BME_CALL_ALERT_FAILED_ANSWERING_REQUEST_STOPPED_TITLE";

/*!
 * "Could not answer request"

 * All translations:

 * @b da@: "Kunne ikke besvare anmodningen"

 * @b en@: "Could not answer request"

 */
static NSString * const BME_CALL_ALERT_FAILED_ANSWERING_UNKNOWN_TITLE = @"BME_CALL_ALERT_FAILED_ANSWERING_UNKNOWN_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_CALL_ALERT_FAILED_CREATING_REQUEST_CANCEL = @"BME_CALL_ALERT_FAILED_CREATING_REQUEST_CANCEL";

/*!
 * "The request could not be created. Please try again."

 * All translations:

 * @b da@: "Anmodningen kunne ikke oprettes. Prøv venligst igen."

 * @b en@: "The request could not be created. Please try again."

 */
static NSString * const BME_CALL_ALERT_FAILED_CREATING_REQUEST_MESSAGE = @"BME_CALL_ALERT_FAILED_CREATING_REQUEST_MESSAGE";

/*!
 * "Could not create request"

 * All translations:

 * @b da@: "Kunne ikke oprette anmodning"

 * @b en@: "Could not create request"

 */
static NSString * const BME_CALL_ALERT_FAILED_CREATING_REQUEST_TITLE = @"BME_CALL_ALERT_FAILED_CREATING_REQUEST_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_CALL_ALERT_FAILED_ANSWERING_UNKNOWN_CANCEL = @"BME_CALL_ALERT_FAILED_ANSWERING_UNKNOWN_CANCEL";

/*!
 * "Please wait..."

 * All translations:

 * @b da@: "Vent venligst..."

 * @b en@: "Please wait..."

 */
static NSString * const BME_CALL_STATUS_PLEASE_WAIT = @"BME_CALL_STATUS_PLEASE_WAIT";

/*!
 * "Answering request..."

 * All translations:

 * @b da@: "Besvarer anmodningen..."

 * @b en@: "Answering request..."

 */
static NSString * const BME_CALL_STATUS_ANSWERING_REQUEST = @"BME_CALL_STATUS_ANSWERING_REQUEST";

/*!
 * "The request could not be answered at this time. Thanks for your help!"

 * All translations:

 * @b da@: "Anmodningen kunne ikke besvares på nuværende tidspunkt. Tak for din hjælp!"

 * @b en@: "The request could not be answered at this time. Thanks for your help!"

 */
static NSString * const BME_CALL_ALERT_FAILED_ANSWERING_UNKNOWN_MESSAGE = @"BME_CALL_ALERT_FAILED_ANSWERING_UNKNOWN_MESSAGE";

/*!
 * "Creating request..."

 * All translations:

 * @b da@: "Opretter anmodning..."

 * @b en@: "Creating request..."

 */
static NSString * const BME_CALL_STATUS_CREATING_REQUEST = @"BME_CALL_STATUS_CREATING_REQUEST";

/*!
 * "Connecting to servers..."

 * All translations:

 * @b da@: "Opretter forbindelse til servere..."

 * @b en@: "Connecting to servers..."

 */
static NSString * const BME_CALL_STATUS_CONNECTING = @"BME_CALL_STATUS_CONNECTING";

/*!
 * "Waiting for other part..."

 * All translations:

 * @b da@: "Venter på modparten..."

 * @b en@: "Waiting for other part..."

 */
static NSString * const BME_CALL_STATUS_CONNECTION_ESTABLISHED = @"BME_CALL_STATUS_CONNECTION_ESTABLISHED";

/*!
 * "Connection failed"

 * All translations:

 * @b da@: "Forbindelsen fejlede"

 * @b en@: "Connection failed"

 */
static NSString * const BME_CALL_STATUS_SESSION_FAILED = @"BME_CALL_STATUS_SESSION_FAILED";

/*!
 * "Failed publishing audio and video"

 * All translations:

 * @b da@: "Mislykkedes at dele lyd og video"

 * @b en@: "Failed publishing audio and video"

 */
static NSString * const BME_CALL_STATUS_FAILED_PUBLISHING = @"BME_CALL_STATUS_FAILED_PUBLISHING";

/*!
 * "Connected to other part"

 * All translations:

 * @b da@: "Forbundet til modpart"

 * @b en@: "Connected to other part"

 */
static NSString * const BME_CALL_SPEECH_DID_SUBSCRIBE = @"BME_CALL_SPEECH_DID_SUBSCRIBE";

/*!
 * "Failed connecting to other part"

 * All translations:

 * @b da@: "Kunne ikke oprette forbindelse til modparten"

 * @b en@: "Failed connecting to other part"

 */
static NSString * const BME_CALL_STATUS_FAILED_SUBSCRIBING = @"BME_CALL_STATUS_FAILED_SUBSCRIBING";

/*!
 * "Disconnecting..."

 * All translations:

 * @b da@: "Afbryder..."

 * @b en@: "Disconnecting..."

 */
static NSString * const BME_CALL_STATUS_DISCONNECTING = @"BME_CALL_STATUS_DISCONNECTING";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_CALL_ALERT_OTHER_PART_DISCONNECTED_CANCEL = @"BME_CALL_ALERT_OTHER_PART_DISCONNECTED_CANCEL";

/*!
 * "The other part has disconnected and the session has ended."

 * All translations:

 * @b da@: "Modparten har afbrudt og sessionen er afsluttet."

 * @b en@: "The other part has disconnected and the session has ended."

 */
static NSString * const BME_CALL_ALERT_OTHER_PART_DISCONNECTED_MESSAGE = @"BME_CALL_ALERT_OTHER_PART_DISCONNECTED_MESSAGE";

/*!
 * "Session ended"

 * All translations:

 * @b da@: "Sessionen sluttede"

 * @b en@: "Session ended"

 */
static NSString * const BME_CALL_ALERT_OTHER_PART_DISCONNECTED_TITLE = @"BME_CALL_ALERT_OTHER_PART_DISCONNECTED_TITLE";

/*!
 * "Back"

 * All translations:

 * @b da@: "Tilbage"

 * @b en@: "Back"

 */
static NSString * const BME_FORGOT_PASSWORD_BACK = @"BME_FORGOT_PASSWORD_BACK";

/*!
 * "Enter your e-mail and we'll send you a new password."

 * All translations:

 * @b da@: "Indtast din e-mail og vi vil sende dig en ny adgangskode."

 * @b en@: "Enter your e-mail and we'll send you a new password."

 */
static NSString * const BME_FORGOT_PASSWORD_DESCRIPTION = @"BME_FORGOT_PASSWORD_DESCRIPTION";

/*!
 * "E-mail"

 * All translations:

 * @b da@: "E-mail"

 * @b en@: "E-mail"

 */
static NSString * const BME_FORGOT_PASSWORD_EMAIL_PLACEHOLDER = @"BME_FORGOT_PASSWORD_EMAIL_PLACEHOLDER";

/*!
 * "Send new password"

 * All translations:

 * @b da@: "Send nyt password"

 * @b en@: "Send new password"

 */
static NSString * const BME_FORGOT_PASSWORD_SEND_PASSWORD = @"BME_FORGOT_PASSWORD_SEND_PASSWORD";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_FORGOT_PASSWORD_ALERT_EMAIL_NOT_VALID_CANCEL = @"BME_FORGOT_PASSWORD_ALERT_EMAIL_NOT_VALID_CANCEL";

/*!
 * "The entered e-mail is not valid. Please change the email and try again."

 * All translations:

 * @b da@: "Den indtastede e-mail er ikke gyldig. Ret e-mail adressen og prøv igen."

 * @b en@: "The entered e-mail is not valid. Please change the email and try again."

 */
static NSString * const BME_FORGOT_PASSWORD_ALERT_EMAIL_NOT_VALID_MESSAGE = @"BME_FORGOT_PASSWORD_ALERT_EMAIL_NOT_VALID_MESSAGE";

/*!
 * "Email is not valid"

 * All translations:

 * @b da@: "E-mail er ikke gyldig"

 * @b en@: "Email is not valid"

 */
static NSString * const BME_FORGOT_PASSWORD_ALERT_EMAIL_NOT_VALID_TITLE = @"BME_FORGOT_PASSWORD_ALERT_EMAIL_NOT_VALID_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_FORGOT_PASSWORD_ALERT_SEND_NEW_PASSWORD_REQUEST_FAILED_CANCEL = @"BME_FORGOT_PASSWORD_ALERT_SEND_NEW_PASSWORD_REQUEST_FAILED_CANCEL";

/*!
 * "The request for a new password could not be sent. Please ensure that you have an active internet connection and try again."

 * All translations:

 * @b da@: "Anmodningen om en ny adgangskode kunne ikke sendes. Sørg for at du har en aktiv internetforbindelse og prøv igen."

 * @b en@: "The request for a new password could not be sent. Please ensure that you have an active internet connection and try again."

 */
static NSString * const BME_FORGOT_PASSWORD_ALERT_SEND_NEW_PASSWORD_REQUEST_FAILED_MESSAGE = @"BME_FORGOT_PASSWORD_ALERT_SEND_NEW_PASSWORD_REQUEST_FAILED_MESSAGE";

/*!
 * "Could not request new password"

 * All translations:

 * @b da@: "Kunne ikke anmode om nyt password"

 * @b en@: "Could not request new password"

 */
static NSString * const BME_FORGOT_PASSWORD_ALERT_SEND_NEW_PASSWORD_REQUEST_FAILED_TITLE = @"BME_FORGOT_PASSWORD_ALERT_SEND_NEW_PASSWORD_REQUEST_FAILED_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_FORGOT_PASSWORD_ALERT_SEND_NEW_PASSWORD_REQUEST_SUCCESS_CANCEL = @"BME_FORGOT_PASSWORD_ALERT_SEND_NEW_PASSWORD_REQUEST_SUCCESS_CANCEL";

/*!
 * "You have received an e-mail with your new password."

 * All translations:

 * @b da@: "Du har modtaget en e-mail med din nye adgangskode."

 * @b en@: "You have received an e-mail with your new password."

 */
static NSString * const BME_FORGOT_PASSWORD_ALERT_SEND_NEW_PASSWORD_REQUEST_SUCCESS_MESSAGE = @"BME_FORGOT_PASSWORD_ALERT_SEND_NEW_PASSWORD_REQUEST_SUCCESS_MESSAGE";

/*!
 * "New password sent"

 * All translations:

 * @b da@: "Nye adgangskode sendt"

 * @b en@: "New password sent"

 */
static NSString * const BME_FORGOT_PASSWORD_ALERT_SEND_NEW_PASSWORD_REQUEST_SUCCESS_TITLE = @"BME_FORGOT_PASSWORD_ALERT_SEND_NEW_PASSWORD_REQUEST_SUCCESS_TITLE";

/*!
 * "Sending request..."

 * All translations:

 * @b da@: "Sender anmodning..."

 * @b en@: "Sending request..."

 */
static NSString * const BME_FORGOT_PASSWORD_OVERLAY_SENDING_REQUEST_FOR_NEW_PASSWORD_TITLE = @"BME_FORGOT_PASSWORD_OVERLAY_SENDING_REQUEST_FOR_NEW_PASSWORD_TITLE";

/*!
 * "Welcome to"

 * All translations:

 * @b da@: "Velkommen til"

 * @b en@: "Welcome to"

 */
static NSString * const BME_FRONT_PAGE_WELCOME_TO = @"BME_FRONT_PAGE_WELCOME_TO";

/*!
 * "Be My Eyes"

 * All translations:

 * @b da@: "Be My Eyes"

 * @b en@: "Be My Eyes"

 */
static NSString * const BME_FRONT_PAGE_APP_NAME = @"BME_FRONT_PAGE_APP_NAME";

/*!
 * "What is your role?"

 * All translations:

 * @b da@: "Hvad er din rolle?"

 * @b en@: "What is your role?"

 */
static NSString * const BME_FRONT_PAGE_ASK_FOR_ROLE = @"BME_FRONT_PAGE_ASK_FOR_ROLE";

/*!
 * "I am sighted"

 * All translations:

 * @b da@: "Jeg er seende"

 * @b en@: "I am sighted"

 */
static NSString * const BME_FRONT_PAGE_SIGHTED_ROLE = @"BME_FRONT_PAGE_SIGHTED_ROLE";

/*!
 * "I am blind"

 * All translations:

 * @b da@: "Jeg er blind"

 * @b en@: "I am blind"

 */
static NSString * const BME_FRONT_PAGE_BLIND_ROLE = @"BME_FRONT_PAGE_BLIND_ROLE";

/*!
 * "Already registered? Log in here."

 * All translations:

 * @b da@: "Allerede registreret? Log ind her."

 * @b en@: "Already registered? Log in here."

 */
static NSString * const BME_FRONT_PAGE_ALREADY_REGISTERED = @"BME_FRONT_PAGE_ALREADY_REGISTERED";

/*!
 * "Back"

 * All translations:

 * @b da@: "Tilbage"

 * @b en@: "Back"

 */
static NSString * const BME_HELPER_INTRO_BACK = @"BME_HELPER_INTRO_BACK";

/*!
 * "Continue"

 * All translations:

 * @b da@: "Fortsæt"

 * @b en@: "Continue"

 */
static NSString * const BME_HELPER_INTRO_CONTINUE = @"BME_HELPER_INTRO_CONTINUE";

/*!
 * "Helping is easy!"

 * All translations:

 * @b da@: "Det er nemt at hjælpe!"

 * @b en@: "Helping is easy!"

 */
static NSString * const BME_HELPER_INTRO_HEADLINE = @"BME_HELPER_INTRO_HEADLINE";

/*!
 * "Help whenever you want, wherever you want."

 * All translations:

 * @b da@: "Hjælp når du vil, uanset hvor du ønsker."

 * @b en@: "Help whenever you want, wherever you want."

 */
static NSString * const BME_HELPER_INTRO_SHORT_DESCRIPTION = @"BME_HELPER_INTRO_SHORT_DESCRIPTION";

/*!
 * "Your phone is open for calls from people who need help when you are signed in."

 * All translations:

 * @b da@: "Din telefon er åben for opkald fra folk, der har brug for hjælp, når du er logget på."

 * @b en@: "Your phone is open for calls from people who need help when you are signed in."

 */
static NSString * const BME_HELPER_INTRO_LONG_DESCRIPTION = @"BME_HELPER_INTRO_LONG_DESCRIPTION";

/*!
 * "Snooze"

 * All translations:

 * @b da@: "Snooze"

 * @b en@: "Snooze"

 */
static NSString * const BME_HELPER_MAIN_SNOOZE_HEADLINE = @"BME_HELPER_MAIN_SNOOZE_HEADLINE";

/*!
 * "You are snoozing the next %@"

 * All translations:

 * @b da@: "Du snoozer i %@"

 * @b en@: "You are snoozing the next %@"

 */
static NSString * const BME_HELPER_MAIN_SNOOZE_STATUS_TEXT = @"BME_HELPER_MAIN_SNOOZE_STATUS_TEXT";

/*!
 * "People Helped"

 * All translations:

 * @b da@: "Folk hjulpet"

 * @b en@: "People Helped"

 */
static NSString * const BME_HELPER_MAIN_HELPED_POINT_DESCRIPTION = @"BME_HELPER_MAIN_HELPED_POINT_DESCRIPTION";

/*!
 * "Points Total"

 * All translations:

 * @b da@: "Totale points"

 * @b en@: "Points Total"

 */
static NSString * const BME_HELPER_MAIN_TOTAL_POINT_DESCRIPTION = @"BME_HELPER_MAIN_TOTAL_POINT_DESCRIPTION";

/*!
 * "New Helper"

 * All translations:

 * @b da@: "Ny hjælper"

 * @b en@: "New Helper"

 */
static NSString * const BME_HELPER_MAIN_LEVEL_NEW_HELPER = @"BME_HELPER_MAIN_LEVEL_NEW_HELPER";

/*!
 * "Promising Helper"

 * All translations:

 * @b da@: "Lovende hjælper"

 * @b en@: "Promising Helper"

 */
static NSString * const BME_HELPER_MAIN_LEVEL_PROMISING_HELPER = @"BME_HELPER_MAIN_LEVEL_PROMISING_HELPER";

/*!
 * "Trusted Helper"

 * All translations:

 * @b da@: "Betroet hjælper"

 * @b en@: "Trusted Helper"

 */
static NSString * const BME_HELPER_MAIN_LEVEL_TRUSTED_HELPER = @"BME_HELPER_MAIN_LEVEL_TRUSTED_HELPER";

/*!
 * "Expert Helper"

 * All translations:

 * @b da@: "Ekspert hjælper"

 * @b en@: "Expert Helper"

 */
static NSString * const BME_HELPER_MAIN_LEVEL_EXPERT_HELPER = @"BME_HELPER_MAIN_LEVEL_EXPERT_HELPER";

/*!
 * "Master Helper"

 * All translations:

 * @b da@: "Mester hjælper"

 * @b en@: "Master Helper"

 */
static NSString * const BME_HELPER_MAIN_LEVEL_MASTER_HELPER = @"BME_HELPER_MAIN_LEVEL_MASTER_HELPER";

/*!
 * "%d points until next level"

 * All translations:

 * @b da@: "%d points til næste niveau"

 * @b en@: "%d points until next level"

 */
static NSString * const BME_HELPER_MAIN_LEVEL_POINTS_NEXT_DESCRIPTION = @"BME_HELPER_MAIN_LEVEL_POINTS_NEXT_DESCRIPTION";

/*!
 * "Successful sign up"

 * All translations:

 * @b da@: "Successful registrering"

 * @b en@: "Successful sign up"

 */
static NSString * const BME_HELPER_MAIN_POINTS_ENTRY_SIGNUP_DESCRIPTION = @"BME_HELPER_MAIN_POINTS_ENTRY_SIGNUP_DESCRIPTION";

/*!
 * "Attempted to help"

 * All translations:

 * @b da@: "Forsøgte at hjælpe"

 * @b en@: "Attempted to help"

 */
static NSString * const BME_HELPER_MAIN_POINTS_ENTRY_ANSWER_PUSH_MESSAGE_DESCRIPTION = @"BME_HELPER_MAIN_POINTS_ENTRY_ANSWER_PUSH_MESSAGE_DESCRIPTION";

/*!
 * "Attempted to help"

 * All translations:

 * @b da@: "Forsøgte at hjælpe"

 * @b en@: "Attempted to help"

 */
static NSString * const BME_HELPER_MAIN_POINTS_ENTRY_ANSWER_PUSH_MESSAGE_TECHNICAL_ERROR_DESCRIPTION = @"BME_HELPER_MAIN_POINTS_ENTRY_ANSWER_PUSH_MESSAGE_TECHNICAL_ERROR_DESCRIPTION";

/*!
 * "Helped a blind person"

 * All translations:

 * @b da@: "Hjalp en blind"

 * @b en@: "Helped a blind person"

 */
static NSString * const BME_HELPER_MAIN_POINTS_ENTRY_FINISH_HELPING_REQUEST_DESCRIPTION = @"BME_HELPER_MAIN_POINTS_ENTRY_FINISH_HELPING_REQUEST_DESCRIPTION";

/*!
 * "Helped 10 in a week"

 * All translations:

 * @b da@: "Hjalp 10 på en uge"

 * @b en@: "Helped 10 in a week"

 */
static NSString * const BME_HELPER_MAIN_POINTS_ENTRY_FINISH_10_HELPING_REQUESTS_IN_A_WEEK_DESCRIPTION = @"BME_HELPER_MAIN_POINTS_ENTRY_FINISH_10_HELPING_REQUESTS_IN_A_WEEK_DESCRIPTION";

/*!
 * "5 high fives in week"

 * All translations:

 * @b da@: "5 high fives på en uge"

 * @b en@: "5 high fives in week"

 */
static NSString * const BME_HELPER_MAIN_POINTS_ENTRY_FINISH_5_HIGH_FIVES_IN_A_WEEK_DESCRIPTION = @"BME_HELPER_MAIN_POINTS_ENTRY_FINISH_5_HIGH_FIVES_IN_A_WEEK_DESCRIPTION";

/*!
 * "Shared on Twitter"

 * All translations:

 * @b da@: "Delte på Twitter"

 * @b en@: "Shared on Twitter"

 */
static NSString * const BME_HELPER_MAIN_POINTS_ENTRY_SHARE_ON_TWITTER_DESCRIPTION = @"BME_HELPER_MAIN_POINTS_ENTRY_SHARE_ON_TWITTER_DESCRIPTION";

/*!
 * "Shared on Facebook"

 * All translations:

 * @b da@: "Delte på Facebook"

 * @b en@: "Shared on Facebook"

 */
static NSString * const BME_HELPER_MAIN_POINTS_ENTRY_SHARE_ON_FACEBOOK_DESCRIPTION = @"BME_HELPER_MAIN_POINTS_ENTRY_SHARE_ON_FACEBOOK_DESCRIPTION";

/*!
 * "Watched video"

 * All translations:

 * @b da@: "Så video"

 * @b en@: "Watched video"

 */
static NSString * const BME_HELPER_MAIN_POINTS_ENTRY_WATCH_VIDEO_DESCRIPTION = @"BME_HELPER_MAIN_POINTS_ENTRY_WATCH_VIDEO_DESCRIPTION";

/*!
 * "The Be My Eyes Network"

 * All translations:

 * @b da@: "Be My Eyes netværket"

 * @b en@: "The Be My Eyes Network"

 */
static NSString * const BME_HELPER_MAIN_COMMUNITY_NETWORK_DESCRIPTION = @"BME_HELPER_MAIN_COMMUNITY_NETWORK_DESCRIPTION";

/*!
 * "Sighted"

 * All translations:

 * @b da@: "Seende"

 * @b en@: "Sighted"

 */
static NSString * const BME_HELPER_MAIN_COMMUNITY_NETWORK_SIGHTED = @"BME_HELPER_MAIN_COMMUNITY_NETWORK_SIGHTED";

/*!
 * "Blind"

 * All translations:

 * @b da@: "Blinde"

 * @b en@: "Blind"

 */
static NSString * const BME_HELPER_MAIN_COMMUNITY_NETWORK_BLIND = @"BME_HELPER_MAIN_COMMUNITY_NETWORK_BLIND";

/*!
 * "Helped"

 * All translations:

 * @b da@: "Hjulpet"

 * @b en@: "Helped"

 */
static NSString * const BME_HELPER_MAIN_COMMUNITY_NETWORK_HELPED = @"BME_HELPER_MAIN_COMMUNITY_NETWORK_HELPED";

/*!
 * "Could not load point"

 * All translations:

 * @b da@: "Kunne ikke indlæse point"

 * @b en@: "Could not load point"

 */
static NSString * const BME_HELPER_MAIN_LOADING_POINT_FAILED = @"BME_HELPER_MAIN_LOADING_POINT_FAILED";

/*!
 * "Retry"

 * All translations:

 * @b da@: "Prøv igen"

 * @b en@: "Retry"

 */
static NSString * const BME_HELPER_MAIN_RETRY_LOADING_POINT = @"BME_HELPER_MAIN_RETRY_LOADING_POINT";

/*!
 * "You are currently active"

 * All translations:

 * @b da@: "Du er i øjeblikket ikke aktiv"

 * @b en@: "You are currently active"

 */
static NSString * const BME_HELPER_MAIN_SNOOZE_STATUS_NOT_SNOOZING_TEXT = @"BME_HELPER_MAIN_SNOOZE_STATUS_NOT_SNOOZING_TEXT";

/*!
 * "Hi %@!"

 * All translations:

 * @b da@: "Hej %@!"

 * @b en@: "Hi %@!"

 */
static NSString * const BME_HELPER_MAIN_GREETING_1 = @"BME_HELPER_MAIN_GREETING_1";

/*!
 * "Ciao %@!"

 * All translations:

 * @b da@: "Ciao %@!"

 * @b en@: "Ciao %@!"

 */
static NSString * const BME_HELPER_MAIN_GREETING_2 = @"BME_HELPER_MAIN_GREETING_2";

/*!
 * "Hello %@!"

 * All translations:

 * @b da@: "Hej %@!"

 * @b en@: "Hello %@!"

 */
static NSString * const BME_HELPER_MAIN_GREETING_3 = @"BME_HELPER_MAIN_GREETING_3";

/*!
 * "Hey %@!"

 * All translations:

 * @b da@: "Hey %@!"

 * @b en@: "Hey %@!"

 */
static NSString * const BME_HELPER_MAIN_GREETING_4 = @"BME_HELPER_MAIN_GREETING_4";

/*!
 * "Howdy %@!"

 * All translations:

 * @b da@: "Hejsa %@!"

 * @b en@: "Howdy %@!"

 */
static NSString * const BME_HELPER_MAIN_GREETING_5 = @"BME_HELPER_MAIN_GREETING_5";

/*!
 * "Your Languages"

 * All translations:

 * @b da@: "Dine Sprog"

 * @b en@: "Your Languages"

 */
static NSString * const BME_LANGUAGES_TITLE = @"BME_LANGUAGES_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_LANGUAGES_ALERT_COULD_NOT_SAVE_CANCEL = @"BME_LANGUAGES_ALERT_COULD_NOT_SAVE_CANCEL";

/*!
 * "The languages could not be saved. Please try again later."

 * All translations:

 * @b da@: "Sprog kunne ikke gemmes. Prøv igen senere."

 * @b en@: "The languages could not be saved. Please try again later."

 */
static NSString * const BME_LANGUAGES_ALERT_COULD_NOT_SAVE_MESSAGE = @"BME_LANGUAGES_ALERT_COULD_NOT_SAVE_MESSAGE";

/*!
 * "Could not save"

 * All translations:

 * @b da@: "Kunne ikke gemme"

 * @b en@: "Could not save"

 */
static NSString * const BME_LANGUAGES_ALERT_COULD_NOT_SAVE_TITLE = @"BME_LANGUAGES_ALERT_COULD_NOT_SAVE_TITLE";

/*!
 * "Back"

 * All translations:

 * @b da@: "Tilbage"

 * @b en@: "Back"

 */
static NSString * const BME_LOGIN_BACK = @"BME_LOGIN_BACK";

/*!
 * "E-mail"

 * All translations:

 * @b da@: "E-mail"

 * @b en@: "E-mail"

 */
static NSString * const BME_LOGIN_EMAIL_PLACEHOLDER = @"BME_LOGIN_EMAIL_PLACEHOLDER";

/*!
 * "Password"

 * All translations:

 * @b da@: "Adgangskode"

 * @b en@: "Password"

 */
static NSString * const BME_LOGIN_PASSWORD_PLACEHOLDER = @"BME_LOGIN_PASSWORD_PLACEHOLDER";

/*!
 * "Log in"

 * All translations:

 * @b da@: "Log på"

 * @b en@: "Log in"

 */
static NSString * const BME_LOGIN_PERFORM_LOG_IN = @"BME_LOGIN_PERFORM_LOG_IN";

/*!
 * "Log in with Facebook"

 * All translations:

 * @b da@: "Log ind med Facebook"

 * @b en@: "Log in with Facebook"

 */
static NSString * const BME_LOGIN_FACEBOOK = @"BME_LOGIN_FACEBOOK";

/*!
 * "Forgot password"

 * All translations:

 * @b da@: "Glemt adgangskode"

 * @b en@: "Forgot password"

 */
static NSString * const BME_LOGIN_FORGOT_PASSWORD = @"BME_LOGIN_FORGOT_PASSWORD";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_LOGIN_ALERT_FACEBOOK_UNKNOWN_ERROR_CANCEL = @"BME_LOGIN_ALERT_FACEBOOK_UNKNOWN_ERROR_CANCEL";

/*!
 * "Please verify that you have an active internet connection and try again."

 * All translations:

 * @b da@: "Kontroller at du har en aktiv internetforbindelse og prøv igen."

 * @b en@: "Please verify that you have an active internet connection and try again."

 */
static NSString * const BME_LOGIN_ALERT_FACEBOOK_UNKNOWN_ERROR_MESSAGE = @"BME_LOGIN_ALERT_FACEBOOK_UNKNOWN_ERROR_MESSAGE";

/*!
 * "An error occurred"

 * All translations:

 * @b da@: "Der opstod en fejl"

 * @b en@: "An error occurred"

 */
static NSString * const BME_LOGIN_ALERT_FACEBOOK_UNKNOWN_ERROR_TITLE = @"BME_LOGIN_ALERT_FACEBOOK_UNKNOWN_ERROR_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_LOGIN_ALERT_FACEBOOK_NOT_LOGGED_IN_CANCEL = @"BME_LOGIN_ALERT_FACEBOOK_NOT_LOGGED_IN_CANCEL";

/*!
 * "You were not logged in. Please try again."

 * All translations:

 * @b da@: "Du blev ikke logget på. Prøv venligst igen."

 * @b en@: "You were not logged in. Please try again."

 */
static NSString * const BME_LOGIN_ALERT_FACEBOOK_NOT_LOGGED_IN_MESSAGE = @"BME_LOGIN_ALERT_FACEBOOK_NOT_LOGGED_IN_MESSAGE";

/*!
 * "Not logged in"

 * All translations:

 * @b da@: "Ikke logget ind"

 * @b en@: "Not logged in"

 */
static NSString * const BME_LOGIN_ALERT_FACEBOOK_NOT_LOGGED_IN_TITLE = @"BME_LOGIN_ALERT_FACEBOOK_NOT_LOGGED_IN_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_LOGIN_ALERT_FACEBOOK_USER_NOT_REGISTERED_CANCEL = @"BME_LOGIN_ALERT_FACEBOOK_USER_NOT_REGISTERED_CANCEL";

/*!
 * "You must first sign up with your Facebook account before you can log in."

 * All translations:

 * @b da@: "Du skal først tilmelde dig med din Facebook-konto, før du kan logge ind."

 * @b en@: "You must first sign up with your Facebook account before you can log in."

 */
static NSString * const BME_LOGIN_ALERT_FACEBOOK_USER_NOT_REGISTERED_MESSAGE = @"BME_LOGIN_ALERT_FACEBOOK_USER_NOT_REGISTERED_MESSAGE";

/*!
 * "Account not registered"

 * All translations:

 * @b da@: "Konto ikke registreret"

 * @b en@: "Account not registered"

 */
static NSString * const BME_LOGIN_ALERT_FACEBOOK_USER_NOT_REGISTERED_TITLE = @"BME_LOGIN_ALERT_FACEBOOK_USER_NOT_REGISTERED_TITLE";

/*!
 * "Please enter both e-mail and password."

 * All translations:

 * @b da@: "Indtast venligst både e-mail og adgangskode."

 * @b en@: "Please enter both e-mail and password."

 */
static NSString * const BME_LOGIN_ALERT_EMPTY_FIELD_MESSAGE = @"BME_LOGIN_ALERT_EMPTY_FIELD_MESSAGE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_LOGIN_ALERT_EMPTY_FIELDS_CANCEL = @"BME_LOGIN_ALERT_EMPTY_FIELDS_CANCEL";

/*!
 * "Empty fields"

 * All translations:

 * @b da@: "Tomme felter"

 * @b en@: "Empty fields"

 */
static NSString * const BME_LOGIN_ALERT_EMPTY_FIELDS_TITLE = @"BME_LOGIN_ALERT_EMPTY_FIELDS_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_LOGIN_ALERT_INCORRECT_CREDENTIALS_CANCEL = @"BME_LOGIN_ALERT_INCORRECT_CREDENTIALS_CANCEL";

/*!
 * "The entered e-mail and password does not match."

 * All translations:

 * @b da@: "Den indtastede e-mail og adgangskode stemmer ikke overens."

 * @b en@: "The entered e-mail and password does not match."

 */
static NSString * const BME_LOGIN_ALERT_INCORRECT_CREDENTIALS_MESSAGE = @"BME_LOGIN_ALERT_INCORRECT_CREDENTIALS_MESSAGE";

/*!
 * "Incorrect credentials"

 * All translations:

 * @b da@: "Forkerte brugeroplysninger"

 * @b en@: "Incorrect credentials"

 */
static NSString * const BME_LOGIN_ALERT_INCORRECT_CREDENTIALS_TITLE = @"BME_LOGIN_ALERT_INCORRECT_CREDENTIALS_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_LOGIN_ALERT_EMAIL_LOGIN_UNKNOWN_ERROR_CANCEL = @"BME_LOGIN_ALERT_EMAIL_LOGIN_UNKNOWN_ERROR_CANCEL";

/*!
 * "Please verify that you have an active internet connection and try again."

 * All translations:

 * @b da@: "Kontroller at du har en aktiv internetforbindelse og prøv igen."

 * @b en@: "Please verify that you have an active internet connection and try again."

 */
static NSString * const BME_LOGIN_ALERT_EMAIL_LOGIN_UNKNOWN_ERROR_MESSAGE = @"BME_LOGIN_ALERT_EMAIL_LOGIN_UNKNOWN_ERROR_MESSAGE";

/*!
 * "An error occurred"

 * All translations:

 * @b da@: "Der opstod en fejl"

 * @b en@: "An error occurred"

 */
static NSString * const BME_LOGIN_ALERT_EMAIL_LOGIN_UNKNOWN_ERROR_TITLE = @"BME_LOGIN_ALERT_EMAIL_LOGIN_UNKNOWN_ERROR_TITLE";

/*!
 * "Logging in..."

 * All translations:

 * @b da@: "Logger ind..."

 * @b en@: "Logging in..."

 */
static NSString * const BME_LOGIN_OVERLAY_LOGGING_IN_TITLE = @"BME_LOGIN_OVERLAY_LOGGING_IN_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_LOGIN_ALERT_FACEBOOK_ACCOUNT_NOT_FOUND_CANCEL = @"BME_LOGIN_ALERT_FACEBOOK_ACCOUNT_NOT_FOUND_CANCEL";

/*!
 * "No Facebook accounts were found on the device. Please add you account in the system settings."

 * All translations:

 * @b da@: "Der blev ikke fundet nogen Facebook konti på enheden. Tilføj venligst din konto i systemindstillinger."

 * @b en@: "No Facebook accounts were found on the device. Please add you account in the system settings."

 */
static NSString * const BME_LOGIN_ALERT_FACEBOOK_ACCOUNT_NOT_FOUND_MESSAGE = @"BME_LOGIN_ALERT_FACEBOOK_ACCOUNT_NOT_FOUND_MESSAGE";

/*!
 * "No account found"

 * All translations:

 * @b da@: "Ingen konto fundet"

 * @b en@: "No account found"

 */
static NSString * const BME_LOGIN_ALERT_FACEBOOK_ACCOUNT_NOT_FOUND_TITLE = @"BME_LOGIN_ALERT_FACEBOOK_ACCOUNT_NOT_FOUND_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_LOGIN_ALERT_NOT_REGISTERED_FOR_REMOTE_NOTIFICATIONS_CANCEL = @"BME_LOGIN_ALERT_NOT_REGISTERED_FOR_REMOTE_NOTIFICATIONS_CANCEL";

/*!
 * "Could not register for remote notifications. This is required for the Be My Eyes application. Please ensure that you have remote notifications enabled in your system settings and try again."

 * All translations:

 * @b da@: "Kunne ikke tilmelde meddelelser. Dette er nødvendig for Be My Eyes appen. Sørg venligst for at du har meddelelser aktiveret i systemindstillingerne, og prøv igen."

 * @b en@: "Could not register for remote notifications. This is required for the Be My Eyes application. Please ensure that you have remote notifications enabled in your system settings and try again."

 */
static NSString * const BME_LOGIN_ALERT_NOT_REGISTERED_FOR_REMOTE_NOTIFICATIONS_MESSAGE = @"BME_LOGIN_ALERT_NOT_REGISTERED_FOR_REMOTE_NOTIFICATIONS_MESSAGE";

/*!
 * "Log in failed"

 * All translations:

 * @b da@: "Log ind mislykkedes"

 * @b en@: "Log in failed"

 */
static NSString * const BME_LOGIN_ALERT_NOT_REGISTERED_FOR_REMOTE_NOTIFICATIONS_TITLE = @"BME_LOGIN_ALERT_NOT_REGISTERED_FOR_REMOTE_NOTIFICATIONS_TITLE";

/*!
 * "Loading request..."

 * All translations:

 * @b da@: "Henter forespørgsel..."

 * @b en@: "Loading request..."

 */
static NSString * const BME_LOGIN_OVERLAY_LOADING_PENDING_REQUEST_TITLE = @"BME_LOGIN_OVERLAY_LOADING_PENDING_REQUEST_TITLE";

/*!
 * "No"

 * All translations:

 * @b da@: "Nej"

 * @b en@: "No"

 */
static NSString * const BME_MAIN_ALERT_MORE_LANGAUGES_BLIND_CANCEL = @"BME_MAIN_ALERT_MORE_LANGAUGES_BLIND_CANCEL";

/*!
 * "Yes, I do"

 * All translations:

 * @b da@: "Ja jeg gør"

 * @b en@: "Yes, I do"

 */
static NSString * const BME_MAIN_ALERT_MORE_LANGAUGES_BLIND_CONFIRM = @"BME_MAIN_ALERT_MORE_LANGAUGES_BLIND_CONFIRM";

/*!
 * "If you know more languages you can select those and be matched with a helper who also knows that language thereby receiving help faster."

 * All translations:

 * @b da@: "Hvis du kender flere sprog kan vælge dem og blive matchet med en hjælper, der også kender sproget dermed modtage hjælp hurtigere."

 * @b en@: "If you know more languages you can select those and be matched with a helper who also knows that language thereby receiving help faster."

 */
static NSString * const BME_MAIN_ALERT_MORE_LANGAUGES_BLIND_MESSAGE = @"BME_MAIN_ALERT_MORE_LANGAUGES_BLIND_MESSAGE";

/*!
 * "Do you know more languages?"

 * All translations:

 * @b da@: "Kender du flere sprog?"

 * @b en@: "Do you know more languages?"

 */
static NSString * const BME_MAIN_ALERT_MORE_LANGAUGES_BLIND_TITLE = @"BME_MAIN_ALERT_MORE_LANGAUGES_BLIND_TITLE";

/*!
 * "No"

 * All translations:

 * @b da@: "Nej"

 * @b en@: "No"

 */
static NSString * const BME_MAIN_ALERT_MORE_LANGAUGES_HELPER_CANCEL = @"BME_MAIN_ALERT_MORE_LANGAUGES_HELPER_CANCEL";

/*!
 * "Yes, I do"

 * All translations:

 * @b da@: "Ja jeg gør"

 * @b en@: "Yes, I do"

 */
static NSString * const BME_MAIN_ALERT_MORE_LANGAUGES_HELPER_CONFIRM = @"BME_MAIN_ALERT_MORE_LANGAUGES_HELPER_CONFIRM";

/*!
 * "If you know more languages, you can select those and you will be matched with blind people who needs help in that language."

 * All translations:

 * @b da@: "Hvis du kender flere sprog, kan du vælge dem, og du vil blive matchet med blinde, der har brug for hjælp på det pågældende sprog."

 * @b en@: "If you know more languages, you can select those and you will be matched with blind people who needs help in that language."

 */
static NSString * const BME_MAIN_ALERT_MORE_LANGAUGES_HELPER_MESSAGE = @"BME_MAIN_ALERT_MORE_LANGAUGES_HELPER_MESSAGE";

/*!
 * "Do you know more languages?"

 * All translations:

 * @b da@: "Kender du flere sprog?"

 * @b en@: "Do you know more languages?"

 */
static NSString * const BME_MAIN_ALERT_MORE_LANGAUGES_HELPER_TITLE = @"BME_MAIN_ALERT_MORE_LANGAUGES_HELPER_TITLE";

/*!
 * "Settings"

 * All translations:

 * @b da@: "Indstillinger"

 * @b en@: "Settings"

 */
static NSString * const BME_MAIN_SETTINGS_BUTTON_ACCESSIBILITY_LABEL = @"BME_MAIN_SETTINGS_BUTTON_ACCESSIBILITY_LABEL";

/*!
 * "Back"

 * All translations:

 * @b da@: "Tilbage"

 * @b en@: "Back"

 */
static NSString * const BME_PRIVACY_POLICY_BACK = @"BME_PRIVACY_POLICY_BACK";

/*!
 * "Yes!"

 * All translations:

 * @b da@: "Ja!"

 * @b en@: "Yes!"

 */
static NSString * const BME_REGISTERED_HEADLINE = @"BME_REGISTERED_HEADLINE";

/*!
 * "You are now registered."

 * All translations:

 * @b da@: "Du er nu registreret."

 * @b en@: "You are now registered."

 */
static NSString * const BME_REGISTERED_DESCRIPTION = @"BME_REGISTERED_DESCRIPTION";

/*!
 * "Log in"

 * All translations:

 * @b da@: "Log på"

 * @b en@: "Log in"

 */
static NSString * const BME_REGISTERED_LOG_IN = @"BME_REGISTERED_LOG_IN";

/*!
 * "Report abuse"

 * All translations:

 * @b da@: "Rapporter misbrug"

 * @b en@: "Report abuse"

 */
static NSString * const BME_REPORT_ABUSE_HEADLINE = @"BME_REPORT_ABUSE_HEADLINE";

/*!
 * "Choose a reason"

 * All translations:

 * @b da@: "Vælg en årsag"

 * @b en@: "Choose a reason"

 */
static NSString * const BME_REPORT_ABUSE_CHOOSE_REASON = @"BME_REPORT_ABUSE_CHOOSE_REASON";

/*!
 * "Report abuse"

 * All translations:

 * @b da@: "Rapporter misbrug"

 * @b en@: "Report abuse"

 */
static NSString * const BME_REPORT_ABUSE_REPORT = @"BME_REPORT_ABUSE_REPORT";

/*!
 * "Skip"

 * All translations:

 * @b da@: "Annuller"

 * @b en@: "Skip"

 */
static NSString * const BME_REPORT_ABUSE_SKIP = @"BME_REPORT_ABUSE_SKIP";

/*!
 * "The person did not want to help."

 * All translations:

 * @b da@: "Personen ønskede ikke at hjælpe."

 * @b en@: "The person did not want to help."

 */
static NSString * const BME_REPORT_ABUSE_REPORT_TEXT_1_BLIND = @"BME_REPORT_ABUSE_REPORT_TEXT_1_BLIND";

/*!
 * "The person was not blind."

 * All translations:

 * @b da@: "Personen var ikke blind."

 * @b en@: "The person was not blind."

 */
static NSString * const BME_REPORT_ABUSE_REPORT_TEXT_1_HELPER = @"BME_REPORT_ABUSE_REPORT_TEXT_1_HELPER";

/*!
 * "The helper acted inappropriate."

 * All translations:

 * @b da@: "Hjælperen handlede upassende."

 * @b en@: "The helper acted inappropriate."

 */
static NSString * const BME_REPORT_ABUSE_REPORT_TEXT_2_BLIND = @"BME_REPORT_ABUSE_REPORT_TEXT_2_BLIND";

/*!
 * "The blind person acted inappropriate."

 * All translations:

 * @b da@: "Den blinde person handlede upassendet."

 * @b en@: "The blind person acted inappropriate."

 */
static NSString * const BME_REPORT_ABUSE_REPORT_TEXT_2_HELPER = @"BME_REPORT_ABUSE_REPORT_TEXT_2_HELPER";

/*!
 * "The reason is not listed."

 * All translations:

 * @b da@: "Grunden er ikke angivet."

 * @b en@: "The reason is not listed."

 */
static NSString * const BME_REPORT_ABUSE_REPORT_TEXT_3_BLIND = @"BME_REPORT_ABUSE_REPORT_TEXT_3_BLIND";

/*!
 * "The reason is not listed."

 * All translations:

 * @b da@: "Grunden er ikke angivet."

 * @b en@: "The reason is not listed."

 */
static NSString * const BME_REPORT_ABUSE_REPORT_TEXT_3_HELPER = @"BME_REPORT_ABUSE_REPORT_TEXT_3_HELPER";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_REPORT_ABUSE_ALERT_REPORTING_FAILED_CANCEL = @"BME_REPORT_ABUSE_ALERT_REPORTING_FAILED_CANCEL";

/*!
 * "The report could not be sent. Please ensure that you have an active internet connection and try again."

 * All translations:

 * @b da@: "Rapporten kunne ikke sendes. Sørg for at du har en aktiv internetforbindelse og prøv igen."

 * @b en@: "The report could not be sent. Please ensure that you have an active internet connection and try again."

 */
static NSString * const BME_REPORT_ABUSE_ALERT_REPORTING_FAILED_MESSAGE = @"BME_REPORT_ABUSE_ALERT_REPORTING_FAILED_MESSAGE";

/*!
 * "Could not report abuse"

 * All translations:

 * @b da@: "Kunne ikke rapportere misbrug"

 * @b en@: "Could not report abuse"

 */
static NSString * const BME_REPORT_ABUSE_ALERT_REPORTING_FAILED_TITLE = @"BME_REPORT_ABUSE_ALERT_REPORTING_FAILED_TITLE";

/*!
 * "Reporting..."

 * All translations:

 * @b da@: "Rapporterer..."

 * @b en@: "Reporting..."

 */
static NSString * const BME_REPORT_ABUSE_OVERLAY_REPORTING_TITLE = @"BME_REPORT_ABUSE_OVERLAY_REPORTING_TITLE";

/*!
 * "Cancel"

 * All translations:

 * @b da@: "Annuller"

 * @b en@: "Cancel"

 */
static NSString * const BME_REPORT_ABUSE_ALERT_CONFIRM_REPORT_ABUSE_CANCEL = @"BME_REPORT_ABUSE_ALERT_CONFIRM_REPORT_ABUSE_CANCEL";

/*!
 * "Confirm"

 * All translations:

 * @b da@: "Bekræft"

 * @b en@: "Confirm"

 */
static NSString * const BME_REPORT_ABUSE_ALERT_CONFIRM_REPORT_ABUSE_CONFIRM = @"BME_REPORT_ABUSE_ALERT_CONFIRM_REPORT_ABUSE_CONFIRM";

/*!
 * "All abuse cases are taken serious and looked into. Are you sure that you want to report the other part for abuse?"

 * All translations:

 * @b da@: "Alle tilfælde af misbrug tages alvorligt og undersøges. Er du sikker på at du vil rapportere modparten?"

 * @b en@: "All abuse cases are taken serious and looked into. Are you sure that you want to report the other part for abuse?"

 */
static NSString * const BME_REPORT_ABUSE_ALERT_CONFIRM_REPORT_ABUSE_MESSAGE = @"BME_REPORT_ABUSE_ALERT_CONFIRM_REPORT_ABUSE_MESSAGE";

/*!
 * "Report Abuse"

 * All translations:

 * @b da@: "Rapporter misbrug"

 * @b en@: "Report Abuse"

 */
static NSString * const BME_REPORT_ABUSE_ALERT_CONFIRM_REPORT_ABUSE_TITLE = @"BME_REPORT_ABUSE_ALERT_CONFIRM_REPORT_ABUSE_TITLE";

/*!
 * "The person did not want to help (Selected)"

 * All translations:

 * @b da@: "Personen ønskede ikke at hjælpe (Valgt)"

 * @b en@: "The person did not want to help (Selected)"

 */
static NSString * const BME_REPORT_ABUSE_ACCESSIBILITY_LABEL_1_SELECTED = @"BME_REPORT_ABUSE_ACCESSIBILITY_LABEL_1_SELECTED";

/*!
 * "The person did not want to help."

 * All translations:

 * @b da@: "Personen ønskede ikke at hjælpe."

 * @b en@: "The person did not want to help."

 */
static NSString * const BME_REPORT_ABUSE_ACCESSIBILITY_LABEL_1 = @"BME_REPORT_ABUSE_ACCESSIBILITY_LABEL_1";

/*!
 * "The helper acted inappropriate (Selected)"

 * All translations:

 * @b da@: "Hjælperen handlede upassende (valgt)"

 * @b en@: "The helper acted inappropriate (Selected)"

 */
static NSString * const BME_REPORT_ABUSE_ACCESSIBILITY_LABEL_2_SELECTED = @"BME_REPORT_ABUSE_ACCESSIBILITY_LABEL_2_SELECTED";

/*!
 * "The helper acted inappropriate."

 * All translations:

 * @b da@: "Hjælperen handlede upassende."

 * @b en@: "The helper acted inappropriate."

 */
static NSString * const BME_REPORT_ABUSE_ACCESSIBILITY_LABEL_2 = @"BME_REPORT_ABUSE_ACCESSIBILITY_LABEL_2";

/*!
 * "The reason is not listed (Selected)"

 * All translations:

 * @b da@: "Grunden er ikke angivet (Valgt)"

 * @b en@: "The reason is not listed (Selected)"

 */
static NSString * const BME_REPORT_ABUSE_ACCESSIBILITY_LABEL_3_SELECTED = @"BME_REPORT_ABUSE_ACCESSIBILITY_LABEL_3_SELECTED";

/*!
 * "The reason is not listed."

 * All translations:

 * @b da@: "Grunden er ikke angivet."

 * @b en@: "The reason is not listed."

 */
static NSString * const BME_REPORT_ABUSE_ACCESSIBILITY_LABEL_3 = @"BME_REPORT_ABUSE_ACCESSIBILITY_LABEL_3";

/*!
 * "API"

 * All translations:

 * @b da@: "API"

 * @b en@: "API"

 */
static NSString * const BME_SECRET_SETTINGS_API_TITLE = @"BME_SECRET_SETTINGS_API_TITLE";

/*!
 * "Changing the API requires the app to be restarted."

 * All translations:

 * @b da@: "Ændre API kræver app skal genstartes."

 * @b en@: "Changing the API requires the app to be restarted."

 */
static NSString * const BME_SECRET_SETTINGS_API_DESCRIPTION = @"BME_SECRET_SETTINGS_API_DESCRIPTION";

/*!
 * "Development"

 * All translations:

 * @b da@: "Development"

 * @b en@: "Development"

 */
static NSString * const BME_SECRET_SETTINGS_API_DEVELOPMENT = @"BME_SECRET_SETTINGS_API_DEVELOPMENT";

/*!
 * "Staging"

 * All translations:

 * @b da@: "Staging"

 * @b en@: "Staging"

 */
static NSString * const BME_SECRET_SETTINGS_API_STAGING = @"BME_SECRET_SETTINGS_API_STAGING";

/*!
 * "Public"

 * All translations:

 * @b da@: "Public"

 * @b en@: "Public"

 */
static NSString * const BME_SECRET_SETTINGS_API_PUBLIC = @"BME_SECRET_SETTINGS_API_PUBLIC";

/*!
 * "Settings"

 * All translations:

 * @b da@: "Indstillinger"

 * @b en@: "Settings"

 */
static NSString * const BME_SETTINGS_HEADLINE = @"BME_SETTINGS_HEADLINE";

/*!
 * "First name"

 * All translations:

 * @b da@: "Fornavn"

 * @b en@: "First name"

 */
static NSString * const BME_SETTINGS_FIRST_NAME = @"BME_SETTINGS_FIRST_NAME";

/*!
 * "Surname"

 * All translations:

 * @b da@: "Efternavn"

 * @b en@: "Surname"

 */
static NSString * const BME_SETTINGS_LAST_NAME = @"BME_SETTINGS_LAST_NAME";

/*!
 * "E-mail"

 * All translations:

 * @b da@: "E-mail"

 * @b en@: "E-mail"

 */
static NSString * const BME_SETTINGS_EMAIL = @"BME_SETTINGS_EMAIL";

/*!
 * "Languages"

 * All translations:

 * @b da@: "Sprog"

 * @b en@: "Languages"

 */
static NSString * const BME_SETTINGS_LANGUAGES = @"BME_SETTINGS_LANGUAGES";

/*!
 * "Add languages"

 * All translations:

 * @b da@: "Tilføj sprog"

 * @b en@: "Add languages"

 */
static NSString * const BME_SETTINGS_ADD_LANGUAGES = @"BME_SETTINGS_ADD_LANGUAGES";

/*!
 * "Give feedback on the app"

 * All translations:

 * @b da@: "Giv feedback på appen"

 * @b en@: "Give feedback on the app"

 */
static NSString * const BME_SETTINGS_FEEDBACK = @"BME_SETTINGS_FEEDBACK";

/*!
 * "Log out"

 * All translations:

 * @b da@: "Log ud"

 * @b en@: "Log out"

 */
static NSString * const BME_SETTINGS_LOG_OUT = @"BME_SETTINGS_LOG_OUT";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_SETTINGS_ALERT_LOG_OUT_FAILED_CANCEL = @"BME_SETTINGS_ALERT_LOG_OUT_FAILED_CANCEL";

/*!
 * "You were not logged out. Please ensure that you have an active internet connection and try again."

 * All translations:

 * @b da@: "Du blev ikke logget ud. Sørg for at du har en aktiv internetforbindelse og prøv igen."

 * @b en@: "You were not logged out. Please ensure that you have an active internet connection and try again."

 */
static NSString * const BME_SETTINGS_ALERT_LOG_OUT_FAILED_MESSAGE = @"BME_SETTINGS_ALERT_LOG_OUT_FAILED_MESSAGE";

/*!
 * "Could not log out"

 * All translations:

 * @b da@: "Kunne ikke logge ud"

 * @b en@: "Could not log out"

 */
static NSString * const BME_SETTINGS_ALERT_LOG_OUT_FAILED_TITLE = @"BME_SETTINGS_ALERT_LOG_OUT_FAILED_TITLE";

/*!
 * "Logging out..."

 * All translations:

 * @b da@: "Logger ud..."

 * @b en@: "Logging out..."

 */
static NSString * const BME_SETTINGS_OVERLAY_LOGGING_OUT_TITLE = @"BME_SETTINGS_OVERLAY_LOGGING_OUT_TITLE";

/*!
 * "Version %@"

 * All translations:

 * @b da@: "Version %@"

 * @b en@: "Version %@"

 */
static NSString * const BME_SETTINGS_VERSION_TITLE = @"BME_SETTINGS_VERSION_TITLE";

/*!
 * "Back"

 * All translations:

 * @b da@: "Tilbage"

 * @b en@: "Back"

 */
static NSString * const BME_SETTINGS_DISMISS_BUTTON_ACCESSIBILITY_LABEL = @"BME_SETTINGS_DISMISS_BUTTON_ACCESSIBILITY_LABEL";

/*!
 * "+%d points"

 * All translations:

 * @b da@: "+%d points"

 * @b en@: "+%d points"

 */
static NSString * const BME_SETTINGS_TASK_POINTS = @"BME_SETTINGS_TASK_POINTS";

/*!
 * "Help a blind person see! #BeMyEyes - the app that connects blind people with sighted helpers through the videocamera in an iPhone."

 * All translations:

 * @b da@: "Hjælp en blind med at se! #BeMyEyes - appen som forbinder blinde med seende hjælpere gennem videokameraet i iPhone."

 * @b en@: "Help a blind person see! #BeMyEyes - the app that connects blind people with sighted helpers through the videocamera in an iPhone."

 */
static NSString * const BME_SETTINGS_TASK_SHARE_MESSAGE = @"BME_SETTINGS_TASK_SHARE_MESSAGE";

/*!
 * "Back"

 * All translations:

 * @b da@: "Tilbage"

 * @b en@: "Back"

 */
static NSString * const BME_SIGN_UP_BACK = @"BME_SIGN_UP_BACK";

/*!
 * "First name"

 * All translations:

 * @b da@: "Fornavn"

 * @b en@: "First name"

 */
static NSString * const BME_SIGN_UP_FIRST_NAME_PLACEHOLDER = @"BME_SIGN_UP_FIRST_NAME_PLACEHOLDER";

/*!
 * "Surname"

 * All translations:

 * @b da@: "Efternavn"

 * @b en@: "Surname"

 */
static NSString * const BME_SIGN_UP_LAST_NAME_PLACEHOLDER = @"BME_SIGN_UP_LAST_NAME_PLACEHOLDER";

/*!
 * "Your first name will be public and presented to helpers."

 * All translations:

 * @b da@: "Dit fornavn vil blive præsenteret til hjælpere."

 * @b en@: "Your first name will be public and presented to helpers."

 */
static NSString * const BME_SIGN_UP_NAME_FOOTER = @"BME_SIGN_UP_NAME_FOOTER";

/*!
 * "E-mail"

 * All translations:

 * @b da@: "E-mail"

 * @b en@: "E-mail"

 */
static NSString * const BME_SIGN_UP_EMAIL_PLACEHOLDER = @"BME_SIGN_UP_EMAIL_PLACEHOLDER";

/*!
 * "Password"

 * All translations:

 * @b da@: "Adgangskode"

 * @b en@: "Password"

 */
static NSString * const BME_SIGN_UP_PASSWORD_PLACEHOLDER = @"BME_SIGN_UP_PASSWORD_PLACEHOLDER";

/*!
 * "Register"

 * All translations:

 * @b da@: "Tilmeld"

 * @b en@: "Register"

 */
static NSString * const BME_SIGN_UP_REGISTER = @"BME_SIGN_UP_REGISTER";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_SIGN_UP_ALERT_EMAIL_ALREADY_REGISTERED_CANCEL = @"BME_SIGN_UP_ALERT_EMAIL_ALREADY_REGISTERED_CANCEL";

/*!
 * "An account with the entered e-mail address already exists."

 * All translations:

 * @b da@: "Der findes allerede en konto med den indtastede e-mail-adresse."

 * @b en@: "An account with the entered e-mail address already exists."

 */
static NSString * const BME_SIGN_UP_ALERT_EMAIL_ALREADY_REGISTERED_MESSAGE = @"BME_SIGN_UP_ALERT_EMAIL_ALREADY_REGISTERED_MESSAGE";

/*!
 * "E-mail already registered"

 * All translations:

 * @b da@: "E-mail allerede registreret"

 * @b en@: "E-mail already registered"

 */
static NSString * const BME_SIGN_UP_ALERT_EMAIL_ALREADY_REGISTERED_TITLE = @"BME_SIGN_UP_ALERT_EMAIL_ALREADY_REGISTERED_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_SIGN_UP_ALERT_EMAIL_NOT_VALID_CANCEL = @"BME_SIGN_UP_ALERT_EMAIL_NOT_VALID_CANCEL";

/*!
 * "The entered e-mail address is not valid."

 * All translations:

 * @b da@: "Den indtastede e-mail adresse er ikke gyldig."

 * @b en@: "The entered e-mail address is not valid."

 */
static NSString * const BME_SIGN_UP_ALERT_EMAIL_NOT_VALID_MESSAGE = @"BME_SIGN_UP_ALERT_EMAIL_NOT_VALID_MESSAGE";

/*!
 * "E-mail is invalid"

 * All translations:

 * @b da@: "E-mail er ugyldig"

 * @b en@: "E-mail is invalid"

 */
static NSString * const BME_SIGN_UP_ALERT_EMAIL_NOT_VALID_TITLE = @"BME_SIGN_UP_ALERT_EMAIL_NOT_VALID_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_SIGN_UP_ALERT_EMPTY_FIELDS_CANCEL = @"BME_SIGN_UP_ALERT_EMPTY_FIELDS_CANCEL";

/*!
 * "Please fill out all information before proceeding."

 * All translations:

 * @b da@: "Udfyld venligst alle oplysninger, før du fortsætter."

 * @b en@: "Please fill out all information before proceeding."

 */
static NSString * const BME_SIGN_UP_ALERT_EMPTY_FIELDS_MESSAGE = @"BME_SIGN_UP_ALERT_EMPTY_FIELDS_MESSAGE";

/*!
 * "Empty fields"

 * All translations:

 * @b da@: "Tomme felter"

 * @b en@: "Empty fields"

 */
static NSString * const BME_SIGN_UP_ALERT_EMPTY_FIELDS_TITLE = @"BME_SIGN_UP_ALERT_EMPTY_FIELDS_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_SIGN_UP_ALERT_PASSWORD_TOO_SHORT_CANCEL = @"BME_SIGN_UP_ALERT_PASSWORD_TOO_SHORT_CANCEL";

/*!
 * "The entered password is too short."

 * All translations:

 * @b da@: "Den indtastede password er for kort."

 * @b en@: "The entered password is too short."

 */
static NSString * const BME_SIGN_UP_ALERT_PASSWORD_TOO_SHORT_MESSAGE = @"BME_SIGN_UP_ALERT_PASSWORD_TOO_SHORT_MESSAGE";

/*!
 * "Password is too short"

 * All translations:

 * @b da@: "Adgangskoden er for kort"

 * @b en@: "Password is too short"

 */
static NSString * const BME_SIGN_UP_ALERT_PASSWORD_TOO_SHORT_TITLE = @"BME_SIGN_UP_ALERT_PASSWORD_TOO_SHORT_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_SIGN_UP_ALERT_PASSWORDS_NOT_MATCHING_CANCEL = @"BME_SIGN_UP_ALERT_PASSWORDS_NOT_MATCHING_CANCEL";

/*!
 * "The entered passwords does not match."

 * All translations:

 * @b da@: "De indtastede adgangskoder stemmer ikke overens."

 * @b en@: "The entered passwords does not match."

 */
static NSString * const BME_SIGN_UP_ALERT_PASSWORDS_NOT_MATCHING_MESSAGE = @"BME_SIGN_UP_ALERT_PASSWORDS_NOT_MATCHING_MESSAGE";

/*!
 * "Passwords not matching"

 * All translations:

 * @b da@: "Adgangskoder matcher ikke"

 * @b en@: "Passwords not matching"

 */
static NSString * const BME_SIGN_UP_ALERT_PASSWORDS_NOT_MATCHING_TITLE = @"BME_SIGN_UP_ALERT_PASSWORDS_NOT_MATCHING_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_SIGN_UP_ALERT_UNKNOWN_ERROR_CANCEL = @"BME_SIGN_UP_ALERT_UNKNOWN_ERROR_CANCEL";

/*!
 * "Your account could not be created. Please verify that you have an active internet connection and try again."

 * All translations:

 * @b da@: "Din konto kunne ikke oprettes. Kontroller, at du har en aktiv internetforbindelse og prøv igen."

 * @b en@: "Your account could not be created. Please verify that you have an active internet connection and try again."

 */
static NSString * const BME_SIGN_UP_ALERT_UNKNOWN_ERROR_MESSAGE = @"BME_SIGN_UP_ALERT_UNKNOWN_ERROR_MESSAGE";

/*!
 * "Could not create account"

 * All translations:

 * @b da@: "Kunne ikke oprette konto"

 * @b en@: "Could not create account"

 */
static NSString * const BME_SIGN_UP_ALERT_UNKNOWN_ERROR_TITLE = @"BME_SIGN_UP_ALERT_UNKNOWN_ERROR_TITLE";

/*!
 * "Logging in..."

 * All translations:

 * @b da@: "Logger ind..."

 * @b en@: "Logging in..."

 */
static NSString * const BME_SIGN_UP_OVERLAY_LOGGING_IN_TITLE = @"BME_SIGN_UP_OVERLAY_LOGGING_IN_TITLE";

/*!
 * "Registering..."

 * All translations:

 * @b da@: "Tilmelder..."

 * @b en@: "Registering..."

 */
static NSString * const BME_SIGN_UP_OVERLAY_REGISTERING_TITLE = @"BME_SIGN_UP_OVERLAY_REGISTERING_TITLE";

/*!
 * "Back"

 * All translations:

 * @b da@: "Tilbage"

 * @b en@: "Back"

 */
static NSString * const BME_SIGN_UP_METHOD_BACK = @"BME_SIGN_UP_METHOD_BACK";

/*!
 * "Become a part of the network"

 * All translations:

 * @b da@: "Bliv en del af netværket"

 * @b en@: "Become a part of the network"

 */
static NSString * const BME_SIGN_UP_METHOD_HEADLINE = @"BME_SIGN_UP_METHOD_HEADLINE";

/*!
 * "Sign up via Facebook"

 * All translations:

 * @b da@: "Tilmeld dig via Facebook"

 * @b en@: "Sign up via Facebook"

 */
static NSString * const BME_SIGN_UP_METHOD_FACEBOOK = @"BME_SIGN_UP_METHOD_FACEBOOK";

/*!
 * "Your first name will be public and presented to helpers."

 * All translations:

 * @b da@: "Dit fornavn vil blive præsenteret til hjælpere"

 * @b en@: "Your first name will be public and presented to helpers."

 */
static NSString * const BME_SIGN_UP_METHOD_FACEBOOK_FOOTER = @"BME_SIGN_UP_METHOD_FACEBOOK_FOOTER";

/*!
 * "You can also"

 * All translations:

 * @b da@: "Du kan også"

 * @b en@: "You can also"

 */
static NSString * const BME_SIGN_UP_METHOD_EMAIL_TOP = @"BME_SIGN_UP_METHOD_EMAIL_TOP";

/*!
 * "register with your e-mail"

 * All translations:

 * @b da@: "Tilmeld dig med din e-mail"

 * @b en@: "register with your e-mail"

 */
static NSString * const BME_SIGN_UP_METHOD_EMAIL_BOTTOM = @"BME_SIGN_UP_METHOD_EMAIL_BOTTOM";

/*!
 * "By continuing you accept the"

 * All translations:

 * @b da@: "Ved fortsætte accepterer du"

 * @b en@: "By continuing you accept the"

 */
static NSString * const BME_SIGN_UP_METHOD_TERMS_AND_AGREEMENTS_TOP = @"BME_SIGN_UP_METHOD_TERMS_AND_AGREEMENTS_TOP";

/*!
 * "Terms and Agreements"

 * All translations:

 * @b da@: "Betingelser for brug"

 * @b en@: "Terms and Agreements"

 */
static NSString * const BME_SIGN_UP_METHOD_TERMS_AND_AGREEMENTS_BOTTOM = @"BME_SIGN_UP_METHOD_TERMS_AND_AGREEMENTS_BOTTOM";

/*!
 * "as well as the"

 * All translations:

 * @b da@: "samt"

 * @b en@: "as well as the"

 */
static NSString * const BME_SIGN_UP_METHOD_PRIVACY_POLICY_TOP = @"BME_SIGN_UP_METHOD_PRIVACY_POLICY_TOP";

/*!
 * "Privacy Policy"

 * All translations:

 * @b da@: "Privatlivspolitik"

 * @b en@: "Privacy Policy"

 */
static NSString * const BME_SIGN_UP_METHOD_PRIVACY_POLICY_BOTTOM = @"BME_SIGN_UP_METHOD_PRIVACY_POLICY_BOTTOM";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_SIGN_UP_METHOD_ALERT_FACEBOOK_EMAIL_ALREADY_REGISTERED_CANCEL = @"BME_SIGN_UP_METHOD_ALERT_FACEBOOK_EMAIL_ALREADY_REGISTERED_CANCEL";

/*!
 * "An account with the e-mail address of the Facebook user has already been registered."

 * All translations:

 * @b da@: "En konto med samme e-mail-adresse som pågældende facebook bruger er allerede registreret."

 * @b en@: "An account with the e-mail address of the Facebook user has already been registered."

 */
static NSString * const BME_SIGN_UP_METHOD_ALERT_FACEBOOK_EMAIL_ALREADY_REGISTERED_MESSAGE = @"BME_SIGN_UP_METHOD_ALERT_FACEBOOK_EMAIL_ALREADY_REGISTERED_MESSAGE";

/*!
 * "E-mail already registered"

 * All translations:

 * @b da@: "E-mail allerede registreret"

 * @b en@: "E-mail already registered"

 */
static NSString * const BME_SIGN_UP_METHOD_ALERT_FACEBOOK_EMAIL_ALREADY_REGISTERED_TITLE = @"BME_SIGN_UP_METHOD_ALERT_FACEBOOK_EMAIL_ALREADY_REGISTERED_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_SIGN_UP_METHOD_ALERT_FACEBOOK_SIGN_UP_UNKNOWN_ERROR_CANCEL = @"BME_SIGN_UP_METHOD_ALERT_FACEBOOK_SIGN_UP_UNKNOWN_ERROR_CANCEL";

/*!
 * "Please verify that you have an active internet connection and try again."

 * All translations:

 * @b da@: "Kontroller at du har en aktiv internetforbindelse og prøv igen."

 * @b en@: "Please verify that you have an active internet connection and try again."

 */
static NSString * const BME_SIGN_UP_METHOD_ALERT_FACEBOOK_SIGN_UP_UNKNOWN_ERROR_MESSAGE = @"BME_SIGN_UP_METHOD_ALERT_FACEBOOK_SIGN_UP_UNKNOWN_ERROR_MESSAGE";

/*!
 * "An error occurred"

 * All translations:

 * @b da@: "Der opstod en fejl"

 * @b en@: "An error occurred"

 */
static NSString * const BME_SIGN_UP_METHOD_ALERT_FACEBOOK_SIGN_UP_UNKNOWN_ERROR_TITLE = @"BME_SIGN_UP_METHOD_ALERT_FACEBOOK_SIGN_UP_UNKNOWN_ERROR_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_SIGN_UP_METHOD_ALERT_NOT_LOGGED_IN_CANCEL = @"BME_SIGN_UP_METHOD_ALERT_NOT_LOGGED_IN_CANCEL";

/*!
 * "Could not authenticate with Facebook."

 * All translations:

 * @b da@: "Kunne ikke godkende med Facebook."

 * @b en@: "Could not authenticate with Facebook."

 */
static NSString * const BME_SIGN_UP_METHOD_ALERT_NOT_LOGGED_IN_MESSAGE = @"BME_SIGN_UP_METHOD_ALERT_NOT_LOGGED_IN_MESSAGE";

/*!
 * "Authentication failed"

 * All translations:

 * @b da@: "Godkendelse mislykkedes"

 * @b en@: "Authentication failed"

 */
static NSString * const BME_SIGN_UP_METHOD_ALERT_NOT_LOGGED_IN_TITLE = @"BME_SIGN_UP_METHOD_ALERT_NOT_LOGGED_IN_TITLE";

/*!
 * "Logging in..."

 * All translations:

 * @b da@: "Logger ind..."

 * @b en@: "Logging in..."

 */
static NSString * const BME_SIGN_UP_METHOD_OVERLAY_LOGGING_IN_TITLE = @"BME_SIGN_UP_METHOD_OVERLAY_LOGGING_IN_TITLE";

/*!
 * "Registering..."

 * All translations:

 * @b da@: "Tilmelder..."

 * @b en@: "Registering..."

 */
static NSString * const BME_SIGN_UP_METHOD_OVERLAY_REGISTERING_TITLE = @"BME_SIGN_UP_METHOD_OVERLAY_REGISTERING_TITLE";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_SIGN_UP_METHOD_ALERT_FACEBOOK_ACCOUNT_NOT_FOUND_CANCEL = @"BME_SIGN_UP_METHOD_ALERT_FACEBOOK_ACCOUNT_NOT_FOUND_CANCEL";

/*!
 * "No Facebook accounts were found on the device. Please add you account in the system settings."

 * All translations:

 * @b da@: "Der blev ikke fundet nogen Facebook konti på enheden. Tilføj venligst din konto i systemindstillinger."

 * @b en@: "No Facebook accounts were found on the device. Please add you account in the system settings."

 */
static NSString * const BME_SIGN_UP_METHOD_ALERT_FACEBOOK_ACCOUNT_NOT_FOUND_MESSAGE = @"BME_SIGN_UP_METHOD_ALERT_FACEBOOK_ACCOUNT_NOT_FOUND_MESSAGE";

/*!
 * "No account found"

 * All translations:

 * @b da@: "Ingen konto fundet"

 * @b en@: "No account found"

 */
static NSString * const BME_SIGN_UP_METHOD_ALERT_FACEBOOK_ACCOUNT_NOT_FOUND_TITLE = @"BME_SIGN_UP_METHOD_ALERT_FACEBOOK_ACCOUNT_NOT_FOUND_TITLE";

/*!
 * "Sign up with e-mail"

 * All translations:

 * @b da@: "tilmelde dig med e-mail"

 * @b en@: "Sign up with e-mail"

 */
static NSString * const BME_SIGN_UP_METHOD_EMAIL_ACCESSIBILITY_HINT = @"BME_SIGN_UP_METHOD_EMAIL_ACCESSIBILITY_HINT";

/*!
 * " "

 * All translations:

 * @b da@: " "

 * @b en@: " "

 */
static NSString * const BME_SIGN_UP_METHOD_EMAIL_ACCESSIBILITY_LABEL = @"BME_SIGN_UP_METHOD_EMAIL_ACCESSIBILITY_LABEL";

/*!
 * "Privacy Policy"

 * All translations:

 * @b da@: "Privatlivspolitik"

 * @b en@: "Privacy Policy"

 */
static NSString * const BME_SIGN_UP_METHOD_PRIVACY_ACCESSIBILITY_HINT = @"BME_SIGN_UP_METHOD_PRIVACY_ACCESSIBILITY_HINT";

/*!
 * " "

 * All translations:

 * @b da@: " "

 * @b en@: " "

 */
static NSString * const BME_SIGN_UP_METHOD_PRIVACY_ACCESSIBILITY_LABEL = @"BME_SIGN_UP_METHOD_PRIVACY_ACCESSIBILITY_LABEL";

/*!
 * "Terms and agreements"

 * All translations:

 * @b da@: "Betingelser for brug"

 * @b en@: "Terms and agreements"

 */
static NSString * const BME_SIGN_UP_METHOD_TERMS_ACCESSIBILITY_HINT = @"BME_SIGN_UP_METHOD_TERMS_ACCESSIBILITY_HINT";

/*!
 * " "

 * All translations:

 * @b da@: " "

 * @b en@: " "

 */
static NSString * const BME_SIGN_UP_METHOD_TERMS_ACCESSIBILITY_LABEL = @"BME_SIGN_UP_METHOD_TERMS_ACCESSIBILITY_LABEL";

/*!
 * "day"

 * All translations:

 * @b da@: "dag"

 * @b en@: "day"

 */
static NSString * const BME_SNOOZE_RELATIVE_DATE_DAY = @"BME_SNOOZE_RELATIVE_DATE_DAY";

/*!
 * "%.0f days"

 * All translations:

 * @b da@: "%.0f dage"

 * @b en@: "%.0f days"

 */
static NSString * const BME_SNOOZE_RELATIVE_DATE_DAYS = @"BME_SNOOZE_RELATIVE_DATE_DAYS";

/*!
 * "hour"

 * All translations:

 * @b da@: "time"

 * @b en@: "hour"

 */
static NSString * const BME_SNOOZE_RELATIVE_DATE_HOUR = @"BME_SNOOZE_RELATIVE_DATE_HOUR";

/*!
 * "%.0f hours"

 * All translations:

 * @b da@: "%.0f timer"

 * @b en@: "%.0f hours"

 */
static NSString * const BME_SNOOZE_RELATIVE_DATE_HOURS = @"BME_SNOOZE_RELATIVE_DATE_HOURS";

/*!
 * "minute"

 * All translations:

 * @b da@: "minut"

 * @b en@: "minute"

 */
static NSString * const BME_SNOOZE_RELATIVE_DATE_MINUTE = @"BME_SNOOZE_RELATIVE_DATE_MINUTE";

/*!
 * "%.0f minutes"

 * All translations:

 * @b da@: "%.0f minutter"

 * @b en@: "%.0f minutes"

 */
static NSString * const BME_SNOOZE_RELATIVE_DATE_MINUTES = @"BME_SNOOZE_RELATIVE_DATE_MINUTES";

/*!
 * "month"

 * All translations:

 * @b da@: "måned"

 * @b en@: "month"

 */
static NSString * const BME_SNOOZE_RELATIVE_DATE_MONTH = @"BME_SNOOZE_RELATIVE_DATE_MONTH";

/*!
 * "%.0f months"

 * All translations:

 * @b da@: "%.0f måneder"

 * @b en@: "%.0f months"

 */
static NSString * const BME_SNOOZE_RELATIVE_DATE_MONTHS = @"BME_SNOOZE_RELATIVE_DATE_MONTHS";

/*!
 * "second"

 * All translations:

 * @b da@: "sekund"

 * @b en@: "second"

 */
static NSString * const BME_SNOOZE_RELATIVE_DATE_SECOND = @"BME_SNOOZE_RELATIVE_DATE_SECOND";

/*!
 * "%.0f seconds"

 * All translations:

 * @b da@: "%.0f sekunder"

 * @b en@: "%.0f seconds"

 */
static NSString * const BME_SNOOZE_RELATIVE_DATE_SECONDS = @"BME_SNOOZE_RELATIVE_DATE_SECONDS";

/*!
 * "week"

 * All translations:

 * @b da@: "uge"

 * @b en@: "week"

 */
static NSString * const BME_SNOOZE_RELATIVE_DATE_WEEK = @"BME_SNOOZE_RELATIVE_DATE_WEEK";

/*!
 * "%.0f weeks"

 * All translations:

 * @b da@: "%.0f uger"

 * @b en@: "%.0f weeks"

 */
static NSString * const BME_SNOOZE_RELATIVE_DATE_WEEKS = @"BME_SNOOZE_RELATIVE_DATE_WEEKS";

/*!
 * "year"

 * All translations:

 * @b da@: "år"

 * @b en@: "year"

 */
static NSString * const BME_SNOOZE_RELATIVE_DATE_YEAR = @"BME_SNOOZE_RELATIVE_DATE_YEAR";

/*!
 * "%.0f years"

 * All translations:

 * @b da@: "%.0f år"

 * @b en@: "%.0f years"

 */
static NSString * const BME_SNOOZE_RELATIVE_DATE_YEARS = @"BME_SNOOZE_RELATIVE_DATE_YEARS";

/*!
 * "Back"

 * All translations:

 * @b da@: "Tilbage"

 * @b en@: "Back"

 */
static NSString * const BME_TERMS_BACK = @"BME_TERMS_BACK";

/*!
 * "OK"

 * All translations:

 * @b da@: "OK"

 * @b en@: "OK"

 */
static NSString * const BME_VIDEO_CANCEL_TITLE = @"BME_VIDEO_CANCEL_TITLE";

/*!
 * "%@ needs your help! Swipe or tap to answer."

 * All translations:

 * @b da@: "%@ har brug for din hjælp! Swipe eller tryk for at besvare."

 * @b en@: "%@ needs your help! Swipe or tap to answer."

 */
static NSString * const PUSH_NOTIFICATION_ANSWER_REQUEST_MESSAGE = @"PUSH_NOTIFICATION_ANSWER_REQUEST_MESSAGE";

/*!
 * "%@ cancelled the request."

 * All translations:

 * @b da@: "%@ annullerede anmodningen."

 * @b en@: "%@ cancelled the request."

 */
static NSString * const PUSH_NOTIFICATION_CANCELLED_REQUEST_MESSAGE = @"PUSH_NOTIFICATION_CANCELLED_REQUEST_MESSAGE";

/*!
 * "The request from %@ was answered."

 * All translations:

 * @b da@: "Anmodning fra %@ blev besvaret."

 * @b en@: "The request from %@ was answered."

 */
static NSString * const PUSH_NOTIFICATION_REQUEST_WAS_ANSWERED_MESSAGE = @"PUSH_NOTIFICATION_REQUEST_WAS_ANSWERED_MESSAGE";

/*!
 * "Answer"

 * All translations:

 * @b da@: "Svar"

 * @b en@: "Answer"

 */
static NSString * const PUSH_NOTIFICATION_ANSWER_REQUEST_ACTION = @"PUSH_NOTIFICATION_ANSWER_REQUEST_ACTION";

                                               
#endif                                         
